### ISSUE TITLE
Please add project files

### ISSUE THREAD

**Issue by Poikilos** [Skandarella/b3dfiles#1]
Hello, I can't fix the issues (mentioned at https://github.com/Skandarella/animalworld/issues/5 ) because I can't edit b3d files. If I import them into Blender, the animations are not imported (or imported as empties using the VirtualBrightPlayz fork: <https://github.com/VirtualBrightPlayz/io_scene_b3d>. What program did you use? Do you have the original project files?

I suggest that you add the answers and license in some sort of readme.md.

**Comment by BobOmbuzal** [comment]
When you merge all objects in Blender, how can you reuse the animations?
I found this video, but it says "Unfortunately you will have to re-animate"
[https://www.youtube.com/watch?v=ko_Q7Tt4-mM](https://www.youtube.com/watch?v=ko_Q7Tt4-mM)
And how would you fix the texture? from 14 obj to 1 obj you got to UV Unwrap again i guess?

**Comment by Poikilos** [comment]
We can't get the animations back without the original project files unless the fork of io_scene_b3d is completed but it is not as of right now. No, the object doesn't have to be unwrapped again after using "join" in blender. The only manual step is vertex groups named the same as the bones and enabling the armature modifier's vertex groups setting. However, we can't get the animated bones without reanimating or getting the project files (not the b3d files, unless there is a program that edits them directly as I also asked, or the io_scene_b3d gets finished to generate animated bones), so that's why I'm asking for the project files.

**Comment by Poikilos** [comment]
Ok, I see the blend files are now at https://github.com/Skandarella/blendfiles as noted at <https://github.com/Skandarella/animalworld/issues/5>. This will not be as simple as I thought. Each bone is a separate armature, so when the mesh is joined it will no longer work. If a mesh has several armatures it gets really confusing and may not export well. I may try to make a Blender script to combine all of the armatures without making the limbs fly into odd places or try detaching the meshes from the bones before joining the bones.

**Comment by BobOmbuzal** [comment]
This is fixed in current master 5.5.0-dev it works with just one texture with and without shaders.
For the old 5.4.* there is an easier fix:
textures = { "textureyak.png", "textureyak.png", ... };
For each object/cube in blender add one texture

**Comment by BobOmbuzal** [comment]
I fixed it in my fork :-)
I just added 20 textures for each... seems to work with 5.4.1
Just the monkey and fox and seahorse should use random textures i guess, but i don't know how...
https://github.com/BobOmbuzal/animalworld

**Comment by Poikilos** [comment]
> This is fixed in current master 5.5.0-dev it works with just one texture with and without shaders. For the old 5.4.* there is an easier fix: textures = { "textureyak.png", "textureyak.png", ... }; For each object/cube in blender add one texture

Thanks for the workaround. It is compatible with any version!

**Comment by Poikilos** [comment]
@BobOmbuzal This thread is getting lost on this issue due to the issue name and how specific it is. Lets please continue discussing this at https://github.com/Skandarella/animalworld/issues/5
